export { About } from "./about";

export { User } from "./user";
export { Review } from "./review";
export { Product, IProduct, IColor } from "./products";
export { Category } from "./category";
export { SubCategory, ISubCategory } from "./subCategory";
export { Brand } from "./brand";
export { Order, IOrder } from "./order";
export { WishList } from "./whishList";
export { Cart } from "./cart";
export { Enquiry } from "./enquiry";
export { Slider } from "./slider";
export { Notification, INotification } from "./notification";
export { CompanyDetails } from "./companyDetails";
export { Team } from "./team";
export { Faq } from "./faq";
export { NewsLetter } from "./newsLetter";
export { Service } from "./service";
export { MetaInfo } from "./metaInfo";
export { ReturnPolicy } from "./returnPolicy";
export { ShippingPolicy } from "./shippingPolicy";
export { PrivacyPolicy } from "./privacyPolicy";
