import { Router } from "express";
import userRoutes from "./userRoutes";
import categoryRoutes from "./categoryRoutes";
import subCategoryRoutes from "./subCategoryRoutes";
import productRoutes from "./productRoutes";
import imageRoutes from "./imageRoutes";
import wishListRoutes from "./wishListRoutes";
import brandRoutes from "./brandRoutes";
import cartRoutes from "./cartRoutes";
import orderRoutes from "./orderRoutes";
import enquiryRoutes from "./enquiryRoutes";
import sliderRoutes from "./sliderRoutes";
import reviewRoutes from "./reviewRoutes";
import notificationRoutes from "./notificationRoutes";
import galleryRoutes from "./galleryRoutes";
import companyDetailRoutes from "./companyDetailRoutes";
import teamRoutes from "./teamRoutes";
import faqRoutes from "./faqRoutes";
import newsLetterRoutes from "./newsLetterRoutes";
import aboutRoutes from "./aboutRoutes";
import serviceRoutes from "./serviceRoutes";
import metaInfoRoutes from "./metaInfoRoutes";

const router = Router();

router.use("/users", userRoutes);
router.use("/category", categoryRoutes);
router.use("/subcategory", subCategoryRoutes);
router.use("/product", productRoutes);
router.use("/image", imageRoutes);
router.use("/brand", brandRoutes);
router.use("/wishlist", wishListRoutes);
router.use("/cart", cartRoutes);
router.use("/order", orderRoutes);
router.use("/enquiry", enquiryRoutes);
router.use("/slider", sliderRoutes);
router.use("/review", reviewRoutes);
router.use("/notification", notificationRoutes);
router.use("/gallery", galleryRoutes);
router.use("/company-detail", companyDetailRoutes);
router.use("/team", teamRoutes);
router.use("/faq", faqRoutes);
router.use("/newsletter", newsLetterRoutes);
router.use("/about", aboutRoutes);
router.use("/service", serviceRoutes);
router.use("/metainfo", metaInfoRoutes);

export default router;
